version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tms_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - tmsnet
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: tms_web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tmsnet
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: tms_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tms
      MYSQL_USER: tms
      MYSQL_PASSWORD: tms
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - tmsnet

networks:
  tmsnet:

volumes:
  dbdata:
